### ISSUE TITLE
Add net context.Context awareness to RoleProvider 

### ISSUE THREAD

**Issue by kevpie** [picatic/go-permission-architect#4]
Enable the use of net/context.Context in PermissionArchitect.

**Comment by interlock** [comment]
Probably Permission Provider as well?

**Comment by kevpie** [comment]
correct!

**Comment by interlock** [comment]
I think we will make this a generic interface{} on Session instead of for the specific calls. This breaks our interfaces less fulfills the intent of passing a context of a request vs a functional net/context around.
